name       : gnome-documents
version    : 3.20.0
release    : 7
source     :
    - https://download.gnome.org/sources/gnome-documents/3.20/gnome-documents-3.20.0.tar.xz : a5fa496c5e80eccb8d2e5bba7f4d7dc4cc6c9f53d5bc028402428771be1237d2
license    : GPL-2.0
component  : office
summary    : Documents Manager for GNOME
description: |
    Documents Manager for GNOME
builddeps  :
    - pkgconfig(evince-view-3.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgdata)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(tracker-control-1.0)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(zapojit-0.0)
    - itstool
rundeps    :
    - tracker
setup      : |
    %configure --disable-static --enable-documentation=no
build      : |
    %make
install    : |
    %make_install
