name       : gnome-documents
version    : 3.18.3
release    : 5
source     :
    - https://download.gnome.org/sources/gnome-documents/3.18/gnome-documents-3.18.3.tar.xz : 16a50d509d43009d58b44b5f6d4d92e155a55dcb22bd8e0fdfd63b8d2ab48b91
license    : GPL-2.0
component  : desktop.gnome
summary    : Documents Manager for GNOME
description: |
    Documents Manager for GNOME
builddeps  :
    - pkgconfig(evince-view-3.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgdata)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(tracker-control-1.0)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(zapojit-0.0)
    - itstool
rundeps:
    - tracker
setup      : |
    %configure --disable-static --enable-documentation=no
build      : |
    %make
install    : |
    %make_install
