name       : gnome-documents
version    : 3.24.3
release    : 17
source     :
    - https://download.gnome.org/sources/gnome-documents/3.24/gnome-documents-3.24.3.tar.xz : c2f920fe1696499ba2594c9ab3328e7f18fa8f60df0273aaad503bbe27eeb9a0
license    : GPL-2.0
component  : office
summary    : Documents Manager for GNOME
description: |
    Documents Manager for GNOME
builddeps  :
    - pkgconfig(evince-view-3.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgdata)
    - pkgconfig(libgepub)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(tracker-control-1.0)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(zapojit-0.0)
    - itstool
rundeps    :
    - gjs
    - libgdata
    - libgepub
    - libzapojit
    - tracker
setup      : |
    %configure --disable-static --enable-documentation=no
build      : |
    %make
install    : |
    %make_install
    sed -i 's/GNOME;GTK;Utility;Core;/Office;/g' $installdir/usr/share/applications/org.gnome.Books.desktop
    sed -i 's/GNOME;GTK;Utility;Core;/Office;/g' $installdir/usr/share/applications/org.gnome.Documents.desktop
