name       : gnome-documents
version    : 3.32.0
release    : 24
source     :
    - https://download.gnome.org/sources/gnome-documents/3.32/gnome-documents-3.32.0.tar.xz : cc2060843e53b6db3372b806536f5df0bfc7abd3c0c35cb5021a3592d76f0dbf
license    : GPL-2.0
component  : office
summary    : Documents Manager for GNOME
description: |
    Documents Manager for GNOME
builddeps  :
    - pkgconfig(evince-view-3.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgdata)
    - pkgconfig(libgepub-0.6)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(tracker-control-2.0)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(zapojit-0.0)
    - desktop-file-utils
    - itstool
rundeps    :
    - gjs
    - libgdata
    - libgepub
    - libzapojit
    - tracker
setup      : |
    %meson_configure -Ddocumentation=false
build      : |
    %ninja_build
install    : |
    %ninja_install
    sed -i 's/GNOME;GTK;Utility;Core;/Office;/g' $installdir/usr/share/applications/org.gnome.Documents.desktop
