name       : gnome-documents
version    : 3.28.0
release    : 22
source     :
    - https://download.gnome.org/sources/gnome-documents/3.28/gnome-documents-3.28.0.tar.xz : 0a320e9713c2ebbf345f9865e19ba7a4e56ecc144da3bdd74000c8345f2a989c
license    : GPL-2.0
component  : office
summary    : Documents Manager for GNOME
description: |
    Documents Manager for GNOME
builddeps  :
    - pkgconfig(evince-view-3.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgdata)
    - pkgconfig(libgepub-0.6)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(tracker-control-2.0)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(zapojit-0.0)
    - desktop-file-utils
    - itstool
rundeps    :
    - gjs
    - libgdata
    - libgepub
    - libzapojit
    - tracker
setup      : |
    %meson_configure -Ddocumentation=false
build      : |
    %ninja_build
install    : |
    %ninja_install
    sed -i 's/GNOME;GTK;Utility;Core;/Office;/g' $installdir/usr/share/applications/org.gnome.Books.desktop
    sed -i 's/GNOME;GTK;Utility;Core;/Office;/g' $installdir/usr/share/applications/org.gnome.Documents.desktop
