name       : gnome-documents
version    : 3.22.0
release    : 10
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-documents/3.22/gnome-documents-3.22.0.tar.xz : edf5cd6b7b7f5847217b60885358030598e551010087d2a9d1765ae6777041ad
license    : GPL-2.0
component  : office
summary    : Documents Manager for GNOME
description: |
    Documents Manager for GNOME
builddeps  :
    - pkgconfig(evince-view-3.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgdata)
    - pkgconfig(libgepub)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(tracker-control-1.0)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(zapojit-0.0)
    - itstool
rundeps    :
    - tracker
setup      : |
    %configure --disable-static --enable-documentation=no
build      : |
    %make
install    : |
    %make_install
    sed -i 's/GNOME;GTK;Utility;Core;/Office;/g' $installdir/usr/share/applications/org.gnome.Books.desktop
    sed -i 's/GNOME;GTK;Utility;Core;/Office;/g' $installdir/usr/share/applications/org.gnome.Documents.desktop
