name       : gnome-documents
version    : 3.22.1
release    : 12
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-documents/3.22/gnome-documents-3.22.1.tar.xz : 3879f1f31c3339cd69355945b4cf217e25dc6ed9cc7577d25d0353e0a1b8e8cb
license    : GPL-2.0
component  : office
summary    : Documents Manager for GNOME
description: |
    Documents Manager for GNOME
builddeps  :
    - pkgconfig(evince-view-3.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgdata)
    - pkgconfig(libgepub)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(tracker-control-1.0)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(zapojit-0.0)
    - itstool
rundeps    :
    - gjs
    - libgepub
    - tracker
setup      : |
    %configure --disable-static --enable-documentation=no
build      : |
    %make
install    : |
    %make_install
    sed -i 's/GNOME;GTK;Utility;Core;/Office;/g' $installdir/usr/share/applications/org.gnome.Books.desktop
    sed -i 's/GNOME;GTK;Utility;Core;/Office;/g' $installdir/usr/share/applications/org.gnome.Documents.desktop
